# Generated by Django 4.0.3 on 2022-04-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articule',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publi',
            new_name='public',
        ),
    ]
